### ISSUE TITLE
panel gets maximized after a new indicator added to chart

### ISSUE THREAD

**Issue by paymanz** [EarnForex/PositionSizeCalculator#18] opened 2021-06-04 13:50 UTC
hi,

there is a small issue when new indicator is added to chart the panel gets maximized by itself ,  if the chart is used for multiple symbols(as in a chart with symbol changer ) it happens for all symbols.

**Comment by EarnForex** [comment] 2021-06-04 15:14
Hello!

What version of the PSC are you using and in which MetaTrader (4 or 5)?
Could you please post exact steps you are taking to reproduce this?
Does it happen with any indicator or just with some?
I couldn't reproduce this myself yet.

**Comment by paymanz** [comment] 2021-06-05 20:12
thanks for respond, not sure why it doesnt happen on your chart! could it be other indicators on my chart tha cause this?!
im attaching a gif to show the issue. 
platform is mt4 , it has happened with different indicators.
![Animation](https://user-images.githubusercontent.com/10323812/120904163-ec162880-c65f-11eb-91c4-8453b5f330fc.gif)

**Comment by EarnForex** [comment] 2021-06-06 10:38
So, the problem appears when you actually change the symbol of the chart, not immediately after you attach some other indicator, right?
What other indicators do you have attached?
Which build of MT4 is that?
Also, please attach the .set file you use for the PSC - perhaps the issue is connected to some input parameter value.
I still cannot reproduce it on my MT4, but you must know that PSC panel's position and settings are saved to a file, which is separate for each symbol, so you shouldn't expect it to look the same when you change the symbol unless you configured it previously for that symbol (which it seems you did in this case).

**Comment by paymanz** [comment] 2021-06-07 12:13
yes when i change TF it happens. mt4 build 1335.

i just tried it with default inputs and clean chart(without any objects) without any other indicators on chart(except the ones i add later) please take a look:
sometimes the same indicator doesn't cause maximizing!
the first 2 indicator i added here has caused the issue previously but here you see they dont. i attach the third indicator also.
[Easy Pips Maker.zip](https://github.com/EarnForex/PositionSizeCalculator/files/6608547/Easy.Pips.Maker.zip)
![Animation](https://user-images.githubusercontent.com/10323812/121014572-61444380-c7af-11eb-8a01-00ececa92894.gif)

**Comment by EarnForex** [comment] 2021-06-07 18:09
Ugh... I've found the reason for this bug. The problem is in the Dialog.mqh file of the standard library in MT4 (it detects the indicator's name incorrectly). I will see if I can fix this from the PSC's code. Thanks for reporting and providing details!

**Comment by EarnForex** [comment] 2021-07-07 18:10
Fixed in 2.38.

**Closed by EarnForex** 2021-07-07 18:10 UTC
